(()=>{'use strict';
const $=id=>document.getElementById(id),KEY='dk_quality_inspections_v1';
let records=JSON.parse(localStorage.getItem(KEY)||'[]'),current=null;let drawingObjectUrl='';
const processes=['Cutting','Punching','Milling','Welding','Grinding','Cleaning','Lacquering / Surface Treatment','Final Inspection'];
const visual=['Cutting size/straightness/burr','All required punching holes and positions','Milling complete, size and surface acceptable','Welding complete, position, porosity/crack/lump','Grinding complete, sharp edges removed','Stiffener type/position/quantity/gap/welding','End Cap / Rail / other components','Final visual inspection and sticker readability'];
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fresh(){return{id:'INS-'+Date.now().toString(36).toUpperCase(),createdAt:new Date().toISOString(),inspector:$('inspector')?.value||localStorage.getItem('dk_inspector')||'',part:{},drawing:{fileName:'',manual:false,checks:[],status:'NOT UPLOADED',fileType:'',fileSize:0,project:'',partNumber:'',drawingNumber:'',revision:'',extraction:'NOT ATTEMPTED',extractedText:'',notes:''},measurement:{instrument:'',calibrationNo:'',method:'',remark:''},approval:{reportNo:'',inspectionDate:'',qualityEngineer:'',decision:'HOLD',remark:'',approvedAt:''},audit:{createdAt:new Date().toISOString(),createdBy:'',updatedAt:'',updatedBy:'',revision:1},traceability:{qrPayload:'',generatedAt:''},dimensions:[],processes:Object.fromEntries(processes.map(x=>[x,{status:'NOT COMPLETED',operator:'',date:'',machine:'',batch:'',remark:''}])),visual:Object.fromEntries(visual.map(x=>[x,{status:'HOLD',inspector:'',date:'',remark:''}])),photos:[],defects:[],result:'HOLD',remark:''}}
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(records));$('saveState').textContent='SAVED LOCALLY'}
function nav(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));if(id==='review')renderReview();if(id==='history')renderHistory();if(id==='report'){renderProfessionalReport();generateTraceabilityQR()}if(id==='traceability')renderTraceabilityResult();if(id==='backup'){$('backupStatus').textContent='Ready to restore a JSON backup.';}window.scrollTo(0,0)}
function init(){['project','partNumber','partName','barcode','drawingNumber','drawingRevision'].forEach(k=>$(k).addEventListener('input',updateIdentityGate));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>nav(b.dataset.tab));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));$('loginBtn').onclick=()=>{const n=$('loginName').value.trim();if(!n)return alert('Inspector name required');localStorage.setItem('dk_inspector',n);$('login').classList.add('hidden');$('app').classList.remove('hidden');startNew();};$('newInspection').onclick=startNew;$('parseSticker').onclick=parseSticker;$('nativeScan').onclick=()=>{if(window.Android?.startNativeScanner)window.Android.startNativeScanner();else alert('Android scanner bridge available only in the Android build. Use manual sticker data here.');};$('drawingFile').onchange=loadDrawing;['drawingProject','drawingPartNumber','drawingDrawingNumber','drawingRevision','drawingNotes','drawingExtractedText'].forEach(k=>$(k).addEventListener('input',syncDrawingFields));$('extractDrawing').onclick=extractDrawingText;$('clearDrawing').onclick=clearDrawing;$('buildCharacteristics').onclick=buildCharacteristicsFromVerifiedText;$('addCharacteristic').onclick=addDimension;['measurementInstrument','calibrationNo','measurementMethod','measurementRemark'].forEach(k=>$(k).addEventListener('input',syncMeasurementMeta));$('markDrawingHold').onclick=()=>{current.drawing.manual=true;renderDrawingChecks()};$('addDefect').onclick=addDefect;$('photoFile').onchange=addPhoto;$('saveInspection').onclick=saveInspection;$('printReport').onclick=()=>window.print();['reportNo','inspectionDate','qualityEngineer','approvalDecision','approvalRemark'].forEach(k=>$(k)?.addEventListener('input',syncApproval));$('exportJson').onclick=exportJson;$('importJson').onchange=importJsonBackup;$('historySearch').oninput=renderHistory;renderDashboard()}
function startNew(){current=fresh();current.inspector=localStorage.getItem('dk_inspector')||'';fillIdentify();renderAll();nav('identify')}
function traceabilityPayload(raw){const text=String(raw||'').trim();if(!text)return null;try{return JSON.parse(text)}catch(e){}try{return JSON.parse(decodeURIComponent(text))}catch(e){}return null}
function findInspectionFromTraceability(payload){if(!payload)return null;const id=String(payload.inspectionId||'').trim();const barcode=String(payload.barcode||'').trim();const project=String(payload.project||'').trim();const partNumber=String(payload.partNumber||'').trim();if(id){const byId=records.find(x=>x.id===id);if(byId)return byId}if(barcode){const matches=records.filter(x=>String(x.part?.barcode||'')===barcode);if(project||partNumber)return matches.find(x=>(!project||x.part?.project===project)&&(!partNumber||x.part?.partNumber===partNumber))||null;return matches[0]||null}return null}
function renderTraceabilityResult(message){if(!$('traceabilityResult'))return;if(message!==undefined){$('traceabilityResult').innerHTML='<div class="trace-result">'+esc(message)+'</div>';return}const raw=$('traceabilityInput')?.value.trim()||'';if(!raw){$('traceabilityResult').innerHTML='<div class="muted">Scan or paste an inspection QR payload to retrieve a saved inspection.</div>';return}const payload=traceabilityPayload(raw);if(!payload){$('traceabilityResult').innerHTML='<div class="trace-result reject">Invalid QR payload. Expected the inspection traceability JSON generated by this system.</div>';return}const found=findInspectionFromTraceability(payload);if(!found){$('traceabilityResult').innerHTML='<div class="trace-result reject">Inspection not found in this device history. Import the saved JSON backup or open the inspection on the device where it was created.</div>';return}$('traceabilityResult').innerHTML='<div class="trace-result ready"><b>'+esc(found.id)+'</b><br>'+esc(found.part?.project||'')+' • '+esc(found.part?.partNumber||'')+' • '+esc(found.part?.barcode||'')+'<br><span class="muted">Status: '+esc(found.result||'HOLD')+'</span></div>'}
function openTraceabilityScan(raw){const payload=traceabilityPayload(raw);if(!payload){renderTraceabilityResult('Invalid QR payload. Scan the Quality Inspection QR generated by this system.');return}const found=findInspectionFromTraceability(payload);if(!found){renderTraceabilityResult('Inspection not found in this device history.');return}current=JSON.parse(JSON.stringify(found));fillIdentify();renderAll();nav('report')}
function startTraceabilityScan(){if(window.Android?.startNativeScanner){window.Android.startNativeScanner();return}renderTraceabilityResult('Native camera scanner is available in the Android build. On browser, paste the QR payload below.')}
window.DKQualityInspection=window.DKQualityInspection||{};window.DKQualityInspection.handleScanResult=openTraceabilityScan;window.onQualityInspectionScanResult=openTraceabilityScan;
function fillIdentify(){const p=current.part;['project','partNumber','partName','barcode','drawingNumber','drawingRevision','unit','inspector'].forEach(k=>$(k).value=p[k]||current[k]||'');updateIdentityGate()}
function updateIdentityGate(){const required=['project','partNumber','partName','barcode','drawingNumber','drawingRevision'];const missing=required.filter(k=>!$(k).value.trim());const el=$('identityGate');el.classList.remove('hidden');if(missing.length){el.classList.remove('ready');el.textContent='⛔ INSPECTION LOCKED — Missing: '+missing.join(', ')+'. Verify Part ↔ Project ↔ Drawing ↔ Revision before continuing.'}else{el.classList.add('ready');el.textContent='✓ IDENTITY VERIFIED — Part ↔ Project ↔ Drawing ↔ Revision ready for inspection.'}}

function parseSticker(){try{const d=window.DKStickerParser.parseSticker($('stickerRaw').value);current.part={project:d.project,partNumber:d.ipo,partName:d.partName,barcode:d.barcode,drawingNumber:'',drawingRevision:'',unit:d.unit,stickerCompany:d.stickerCompany,width:d.width,length:d.length};fillIdentify();if(!current.dimensions.length){current.dimensions=[{id:'DIM-01',name:'Overall Length',nominal:d.length,tol:1,actual:'',unit:'mm',remark:''},{id:'DIM-02',name:'Overall Width',nominal:d.width,tol:1,actual:'',unit:'mm',remark:''}]};renderAll();alert('Sticker parsed. Verify Project/Part/Drawing before continuing.')}catch(e){alert(e.message)}}
function syncDrawingFields(){if(!current)return;current.drawing.project=$('drawingProject').value.trim();current.drawing.partNumber=$('drawingPartNumber').value.trim();current.drawing.drawingNumber=$('drawingDrawingNumber').value.trim();current.drawing.revision=$('drawingRevision').value.trim();current.drawing.notes=$('drawingNotes').value.trim();current.drawing.extractedText=$('drawingExtractedText').value;renderDrawingChecks();renderReview()}
function drawingMatchesIdentity(){const p=current.part||{};const d=current.drawing||{};return !!(p.project&&p.partNumber&&p.drawingNumber&&p.drawingRevision&&d.project&&d.partNumber&&d.drawingNumber&&d.revision&&d.project===p.project&&d.partNumber===p.partNumber&&d.drawingNumber===p.drawingNumber&&d.revision===p.drawingRevision)}
function clearDrawing(){if(drawingObjectUrl)URL.revokeObjectURL(drawingObjectUrl);drawingObjectUrl='';current.drawing={fileName:'',manual:false,checks:[],status:'NOT UPLOADED',fileType:'',fileSize:0,project:'',partNumber:'',drawingNumber:'',revision:'',extraction:'NOT ATTEMPTED',extractedText:'',notes:''};$('drawingFile').value='';$('drawingMeta').textContent='No drawing uploaded.';$('drawingPreview').innerHTML='';fillDrawingFields();renderDrawingChecks();renderReview()}
function fillDrawingFields(){if(!current)return;[['drawingProject',current.drawing.project],['drawingPartNumber',current.drawing.partNumber],['drawingDrawingNumber',current.drawing.drawingNumber],['drawingRevision',current.drawing.revision],['drawingNotes',current.drawing.notes],['drawingExtractedText',current.drawing.extractedText]].forEach(([id,v])=>$(id).value=v||'')}
function loadDrawing(e){const f=e.target.files[0];if(!f)return;if(!/^application\/pdf$|^image\//.test(f.type)){alert('Only PDF or drawing image is allowed.');e.target.value='';return}if(drawingObjectUrl)URL.revokeObjectURL(drawingObjectUrl);drawingObjectUrl=URL.createObjectURL(f);current.drawing.fileName=f.name;current.drawing.fileType=f.type;current.drawing.fileSize=f.size;current.drawing.status='UPLOADED';current.drawing.extraction='NOT ATTEMPTED';$('drawingMeta').textContent=f.name+' • '+Math.max(1,Math.round(f.size/1024))+' KB • '+f.type;$('drawingPreview').innerHTML=f.type==='application/pdf'?'<iframe title="Approved drawing PDF" src="'+drawingObjectUrl+'"></iframe>':'<img src="'+drawingObjectUrl+'" alt="Approved engineering drawing">';fillDrawingFields();renderDrawingChecks();renderReview()}
async function extractDrawingText(){if(!current.drawing.fileName){alert('Upload the approved drawing first.');return}current.drawing.extraction='MANUAL VERIFICATION REQUIRED';current.drawing.manual=true;$('drawingExtractStatus').textContent='Manual Verification Required — browser-safe extraction is not being guessed.';renderDrawingChecks();renderReview()}

function renderDrawingChecks(){if(!current)return;const labels=['Drawing file uploaded','Drawing Number verified','Revision verified','Project/Part mapping verified','Dimensions/tolerances readable'];$('drawingChecks').innerHTML=labels.map((x,i)=>'<label class="check-item"><span>'+x+'</span><select data-dc="'+i+'"><option>PASS</option><option>HOLD</option></select></label>').join('');const values=[current.drawing.status==='UPLOADED'?'PASS':'HOLD',current.drawing.checks[1]||'HOLD',current.drawing.checks[2]||'HOLD',current.drawing.checks[3]||'HOLD',current.drawing.checks[4]||'HOLD'];document.querySelectorAll('[data-dc]').forEach(s=>{const i=+s.dataset.dc;s.value=values[i];s.disabled=i===0;s.onchange=()=>{current.drawing.checks[i]=s.value;renderReview()}});$('drawingExtractStatus').textContent=current.drawing.extraction==='NOT ATTEMPTED'?'Extraction status: Pending verification':current.drawing.extraction.replaceAll('_',' ')}
function syncMeasurementMeta(){if(!current)return;current.measurement={instrument:$('measurementInstrument').value.trim(),calibrationNo:$('calibrationNo').value.trim(),method:$('measurementMethod').value.trim(),remark:$('measurementRemark').value.trim()};renderReview()}
function fillMeasurementMeta(){if(!current||!current.measurement)return;[['measurementInstrument',current.measurement.instrument],['calibrationNo',current.measurement.calibrationNo],['measurementMethod',current.measurement.method],['measurementRemark',current.measurement.remark]].forEach(([id,v])=>$(id).value=v||'')}
function addDimension(seed){const d=seed||{id:'DIM-'+String(current.dimensions.length+1).padStart(2,'0'),name:'New Characteristic',type:'DIMENSION',reference:'',nominal:'',tol:'',actual:'',unit:'mm',remark:'',critical:false};current.dimensions.push(d);renderDimensions()}
function buildCharacteristicsFromVerifiedText(){const text=$('drawingExtractedText').value.trim();if(!text){alert('Enter verified drawing information first. Do not enter guessed values.');return}const lines=text.split(/\\n|\\r/).map(x=>x.trim()).filter(Boolean);const found=[];const re=/^(.+?)\\s*[:|=]\\s*(-?\\d+(?:\\.\\d+)?)\\s*(?:mm)?\\s*(?:±\\s*(\\d+(?:\\.\\d+)?))?\\s*(?:mm)?$/i;lines.forEach((line)=>{const m=line.match(re);if(m){found.push({name:m[1].trim(),type:'DIMENSION',reference:'Verified drawing text',nominal:m[2],tol:m[3]||'',actual:'',unit:'mm',remark:'',critical:false})}});if(!found.length){alert('No reliably structured dimension line found. Manual characteristic entry is required.');current.drawing.manual=true;current.drawing.extraction='MANUAL VERIFICATION REQUIRED';renderReview();return}found.forEach(x=>addDimension(x));current.drawing.extraction='VERIFIED DATA RECORDED';current.drawing.manual=false;renderDrawingChecks();renderReview();alert(found.length+' verified characteristic(s) added. Review each one before inspection.')}

function dimResult(d){if(d.actual===''||d.nominal===''||d.tol==='')return'HOLD';const a=Number(d.actual),n=Number(d.nominal),t=Math.abs(Number(d.tol));if(!Number.isFinite(a)||!Number.isFinite(n)||!Number.isFinite(t))return'HOLD';return a>=n-t&&a<=n+t?'PASS':'REJECT'}
function measurementRange(d){if(d.nominal===''||d.tol==='')return{low:'',high:''};const n=Number(d.nominal),t=Math.abs(Number(d.tol));if(!Number.isFinite(n)||!Number.isFinite(t))return{low:'',high:''};return{low:n-t,high:n+t}}
function measurementStats(){const total=current.dimensions.length,done=current.dimensions.filter(d=>d.actual!=='').length,critical=current.dimensions.filter(d=>d.critical).length,criticalDone=current.dimensions.filter(d=>d.critical&&d.actual!=='').length;return{total,done,critical,criticalDone}}
function renderDimensions(){ $('dimensionBody').innerHTML=current.dimensions.map((d,i)=>'<tr><td>'+esc(d.id)+'</td><td><input data-d="'+i+'" data-k="name" value="'+esc(d.name)+'"><select data-d="'+i+'" data-k="type"><option>DIMENSION</option><option>HOLE</option><option>MILLING</option><option>STIFFENER</option><option>POSITION</option><option>ANGLE</option><option>OTHER</option></select></td><td><input data-d="'+i+'" data-k="reference" value="'+esc(d.reference||'')+'" placeholder="Drawing ref"></td><td><input type="number" data-d="'+i+'" data-k="nominal" value="'+esc(d.nominal)+'"></td><td><input type="number" data-d="'+i+'" data-k="tol" value="'+esc(d.tol)+'"></td><td><input type="number" data-d="'+i+'" data-k="actual" value="'+esc(d.actual)+'"></td><td><input data-d="'+i+'" data-k="unit" value="'+esc(d.unit)+'"></td><td>'+esc(measurementRange(d).low===''?'—':measurementRange(d).low.toFixed(3))+'</td><td>'+esc(measurementRange(d).high===''?'—':measurementRange(d).high.toFixed(3))+'</td><td><label><input type="checkbox" data-d="'+i+'" data-k="critical" '+(d.critical?'checked':'')+'> Critical</label></td><td class="'+dimResult(d).toLowerCase()+'">'+dimResult(d)+'</td><td><input data-d="'+i+'" data-k="remark" value="'+esc(d.remark)+'"></td><td><button class="danger" data-del="'+i+'">×</button></td></tr>').join('');document.querySelectorAll('[data-d]').forEach(x=>x.onchange=()=>{current.dimensions[+x.dataset.d][x.dataset.k]=x.type==='checkbox'?x.checked:x.value;renderDimensions();renderReview()});document.querySelectorAll('[data-del]').forEach(x=>x.onclick=()=>{current.dimensions.splice(+x.dataset.del,1);renderDimensions();renderReview()});const rs=current.dimensions.map(dimResult);$('dimensionResult').textContent=rs.length===0?'PENDING':rs.includes('REJECT')?'REJECT':rs.includes('HOLD')?'HOLD':'PASS';const ms=measurementStats();if($('measurementProgress'))$('measurementProgress').textContent=ms.done+' / '+ms.total+' completed';if($('criticalSummary'))$('criticalSummary').textContent='Critical: '+ms.critical+' ('+ms.criticalDone+' measured)'}
function processRecord(p){
 const v=current.processes?.[p];
 if(v&&typeof v==='object')return{status:v.status||'NOT COMPLETED',operator:v.operator||'',date:v.date||'',machine:v.machine||'',batch:v.batch||'',remark:v.remark||''};
 return{status:v||'NOT COMPLETED',operator:'',date:'',machine:'',batch:'',remark:''};
}
function syncProcessField(p,k,value){if(!current)return;const v=processRecord(p);v[k]=value;current.processes[p]=v;renderReview()}
function renderProcesses(){
 $('processBody').innerHTML=processes.map((p,i)=>{const v=processRecord(p);return '<div class="process-card"><div class="process-head"><div><b>'+esc(p)+'</b><br><small class="muted">Mandatory process verification & traceability</small></div><select class="status-select" data-proc="'+esc(p)+'"><option>COMPLETED</option><option>NOT COMPLETED</option><option>NOT APPLICABLE</option><option>HOLD</option></select></div><div class="process-fields"><label>Operator / Employee<input data-pf="'+i+'" data-pk="operator" value="'+esc(v.operator)+'" placeholder="Name / ID"></label><label>Process Date<input type="date" data-pf="'+i+'" data-pk="date" value="'+esc(v.date)+'"></label><label>Machine / Line<input data-pf="'+i+'" data-pk="machine" value="'+esc(v.machine)+'" placeholder="Machine / Line"></label><label>Batch / Job / Lot<input data-pf="'+i+'" data-pk="batch" value="'+esc(v.batch)+'" placeholder="Batch / Job / Lot"></label><label class="wide">Process Remark<textarea data-pf="'+i+'" data-pk="remark" placeholder="Process result / handover remark">'+esc(v.remark)+'</textarea></label></div></div>'}).join('');
 document.querySelectorAll('[data-proc]').forEach(x=>{const p=x.dataset.proc;x.value=processRecord(p).status;x.onchange=()=>{syncProcessField(p,'status',x.value);renderProcesses()}});
 document.querySelectorAll('[data-pf]').forEach(x=>x.onchange=()=>{const p=processes[+x.dataset.pf];syncProcessField(p,x.dataset.pk,x.value)});
}

function normalizeVisualRecords(){visual.forEach(v=>{current.visual[v]=visualRecord(v)});current.photos=current.photos||[];current.defects=(current.defects||[]).map(d=>{d.rework=d.rework||{status:d.status==='RECHECK'?'COMPLETED':'PENDING',action:'',by:'',date:'',remark:''};d.reportedBy=d.reportedBy||current.inspector||localStorage.getItem('dk_inspector')||'';d.reportedAt=d.reportedAt||current.createdAt||new Date().toISOString();return d});current.audit=current.audit||{createdAt:current.createdAt||new Date().toISOString(),createdBy:current.inspector||'',updatedAt:'',updatedBy:'',revision:1}}
function visualRecord(v){
 const x=current.visual?.[v];
 if(x&&typeof x==='object')return{status:x.status||'HOLD',inspector:x.inspector||'',date:x.date||'',remark:x.remark||''};
 return{status:x||'HOLD',inspector:'',date:'',remark:''};
}
function syncVisualField(v,k,value){const x=visualRecord(v);x[k]=value;current.visual[v]=x;renderReview()}
function renderVisual(){
 $('visualBody').innerHTML=visual.map((v,i)=>{const x=visualRecord(v);return '<div class="visual-card"><div class="visual-head"><b>'+esc(v)+'</b><select data-vis="'+i+'"><option>PASS</option><option>FAIL</option><option>HOLD</option><option>NOT APPLICABLE</option></select></div><div class="visual-fields"><label>Inspector<input data-vf="'+i+'" data-vk="inspector" value="'+esc(x.inspector)+'" placeholder="Name / ID"></label><label>Inspection Date<input type="date" data-vf="'+i+'" data-vk="date" value="'+esc(x.date)+'"></label><label>Remark<textarea data-vf="'+i+'" data-vk="remark" placeholder="Observation / specification reference">'+esc(x.remark)+'</textarea></label></div></div>'}).join('');
 document.querySelectorAll('[data-vis]').forEach(x=>{const v=visual[+x.dataset.vis];x.value=visualRecord(v).status;x.onchange=()=>{syncVisualField(v,'status',x.value);renderVisual()}});
 document.querySelectorAll('[data-vf]').forEach(x=>x.onchange=()=>{const v=visual[+x.dataset.vf];syncVisualField(v,x.dataset.vk,x.value)});
}
function addPhoto(e){const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('image/')){alert('Only image evidence is allowed.');e.target.value='';return}const r=new FileReader();r.onload=()=>{current.photos.push({id:'PHOTO-'+Date.now().toString(36).toUpperCase(),category:$('photoCategory').value,name:f.name,data:r.result,addedAt:new Date().toISOString(),inspector:localStorage.getItem('dk_inspector')||''});renderPhotos();renderReview()};r.readAsDataURL(f);e.target.value=''}
function renderPhotos(){$('photoList').innerHTML=current.photos.map((p,i)=>'<div class="photo-card"><div><b>'+esc(p.id)+'</b> • '+esc(p.category)+'</div><small>'+esc(p.name)+' • '+esc(p.inspector||'')+' • '+esc(p.addedAt||'')+'</small><br><img src="'+p.data+'"><br><button class="danger" data-photo-del="'+i+'">Remove</button></div>').join('')||'<div class="muted">No photos yet.</div>';document.querySelectorAll('[data-photo-del]').forEach(b=>b.onclick=()=>{current.photos.splice(+b.dataset.photoDel,1);renderPhotos();renderReview()})}
function addDefect(){const type=$('defectType').value.trim();if(!type)return alert('Defect type required');current.defects.push({id:'DEF-'+Date.now().toString(36).toString().toUpperCase(),process:$('defectProcess').value,type,actual:$('defectActual').value,remark:$('defectRemark').value,status:'OPEN',reportedBy:localStorage.getItem('dk_inspector')||current.inspector||'',reportedAt:new Date().toISOString(),rework:{status:'PENDING',action:'',by:'',date:'',remark:''}});$('defectType').value='';$('defectActual').value='';$('defectRemark').value='';renderDefects();renderReview()}
function renderDefects(){$('defectList').innerHTML=current.defects.map((d,i)=>'<div class="defect-card"><b>'+esc(d.id)+' • '+esc(d.type)+'</b><br><span>'+esc(d.process)+' — '+esc(d.status)+'</span><br>'+esc(d.actual)+'<br><small>Reported by: '+esc(d.reportedBy||'')+' • '+esc(d.reportedAt||'')+'</small><br><small>'+esc(d.remark)+'</small><div class="rework-fields"><label>Rework Action<input data-rw="'+i+'" data-rk="action" value="'+esc(d.rework?.action||'')" placeholder="Correction / rework action"></label><label>Rework By<input data-rw="'+i+'" data-rk="by" value="'+esc(d.rework?.by||'')" placeholder="Employee / operator"></label><label>Rework Date<input type="date" data-rw="'+i+'" data-rk="date" value="'+esc(d.rework?.date||'')"></label><label>Rework Remark<textarea data-rw="'+i+'" data-rk="remark">'+esc(d.rework?.remark||'')+'</textarea></label></div><button class="danger" data-close="'+i+'">Close after rework / recheck</button></div>').join('')||'<div class="muted">No defects.</div>';document.querySelectorAll('[data-rw]').forEach(x=>x.onchange=()=>{const d=current.defects[+x.dataset.rw];d.rework=d.rework||{status:'PENDING'};d.rework[x.dataset.rk]=x.value;renderReview()});document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>{const d=current.defects[+x.dataset.close];if(!d.rework?.action||!d.rework?.by||!d.rework?.date){alert('Complete rework action, person and date before recheck.');return}d.status='RECHECK';d.rework.status='COMPLETED';renderDefects();renderReview()})}
function gates(){updateIdentityGate();const dims=current.dimensions.map(dimResult);const measurementMetaOk=!!(current.measurement?.instrument&&current.measurement?.method);const proc=processes.every(p=>['COMPLETED','NOT APPLICABLE'].includes(processRecord(p).status));const trace=processes.every(p=>{const v=processRecord(p);return v.status==='NOT APPLICABLE'||(v.status==='COMPLETED'&&v.operator&&v.date&&v.machine&&v.batch)});const vis=visual.every(v=>['PASS','NOT APPLICABLE'].includes(visualRecord(v).status));const visualTrace=visual.every(v=>{const x=visualRecord(v);return x.status==='NOT APPLICABLE'||(x.status==='PASS'&&x.inspector&&x.date)});const mismatch=['project','partNumber','partName','barcode','drawingNumber','drawingRevision'].some(k=>!$(k).value.trim());const drawingHold=current.drawing.manual||current.drawing.status!=='UPLOADED'||current.drawing.checks.length<5||current.drawing.checks.some((x,i)=>i>0&&x!=='PASS')||current.drawing.extraction==='MANUAL VERIFICATION REQUIRED';const criticalDef=current.defects.some(d=>d.status==='OPEN');return[{name:'Part ↔ Drawing identity verified',ok:!mismatch&&!drawingHold},{name:'Mandatory processes completed',ok:proc},{name:'Process traceability complete',ok:trace},{name:'Measurement record complete',ok:measurementMetaOk},{name:'Dimensions within tolerance',ok:dims.length>0&&!dims.includes('REJECT')&&!dims.includes('HOLD')},{name:'Manual / visual inspection passed',ok:vis},{name:'Visual inspection traceability complete',ok:visualTrace},{name:'No open critical defect',ok:!criticalDef},{name:'Final inspection completed',ok:['COMPLETED','NOT APPLICABLE'].includes(processRecord('Final Inspection').status)}]}
function finalStatus(){const g=gates();if(current.dimensions.some(d=>dimResult(d)==='REJECT')||current.defects.some(d=>d.status==='OPEN'))return'REJECT';if(g.every(x=>x.ok))return'PASS';return'HOLD'}
function renderReview(){fillApproval();if($('reportHeaderId'))$('reportHeaderId').textContent='Inspection ID: '+(current?.id||'—');if($('reportHeaderPart'))$('reportHeaderPart').textContent='Part: '+(current?.part?.partNumber||'—')+' • '+(current?.part?.partName||'—');if($('reportHeaderDrawing'))$('reportHeaderDrawing').textContent='Drawing: '+(current?.drawing?.drawingNumber||'—')+' • Rev '+(current?.drawing?.revision||'—');const g=gates();$('gateChecks').innerHTML=g.map(x=>'<div class="check-item"><span>'+x.name+'</span><b class="'+(x.ok?'ok':'hold')+'">'+(x.ok?'PASS':'HOLD')+'</b></div>').join('');const s=finalStatus();$('finalResult').textContent=s;$('finalResult').className='result '+s.toLowerCase();if($('reportSystemResult')){$('reportSystemResult').textContent=s;$('reportSystemResult').className=s.toLowerCase()}$('reportId').textContent=current.savedAt?'Inspection ID: '+current.id:''}
function syncApproval(){if(!current)return;current.approval=current.approval||{};current.approval.reportNo=$('reportNo').value.trim();current.approval.inspectionDate=$('inspectionDate').value;current.approval.qualityEngineer=$('qualityEngineer').value.trim();current.approval.decision=$('approvalDecision').value;current.approval.remark=$('approvalRemark').value.trim();renderReview()}
function fillApproval(){const a=current.approval||{};[['reportNo',a.reportNo||current.id],['inspectionDate',a.inspectionDate||new Date(current.createdAt||Date.now()).toISOString().slice(0,10)],['qualityEngineer',a.qualityEngineer],['approvalDecision',a.decision||'HOLD'],['approvalRemark',a.remark]].forEach(([id,v])=>{if($(id))$(id).value=v||''})}
function approvalDecisionValid(status){const d=current.approval?.decision||'HOLD';if(d==='PASS')return status==='PASS'&&!!current.approval.qualityEngineer&&!!current.approval.inspectionDate;return d==='REJECT'||d==='HOLD'}
function saveInspection(){processes.forEach(p=>current.processes[p]=processRecord(p));syncApproval();current.remark=$('finalRemark').value;current.result=finalStatus();current.audit=current.audit||{createdAt:current.createdAt,createdBy:current.inspector||'',revision:1};current.audit.updatedAt=new Date().toISOString();current.audit.updatedBy=localStorage.getItem('dk_inspector')||current.inspector||'';current.audit.revision=Number(current.audit.revision||1)+1;if(!approvalDecisionValid(current.result)){alert('Final approval is not valid. PASS requires all inspection gates plus Quality Engineer, inspection date and PASS decision.');return}current.approval.approvedAt=new Date().toISOString();current.inspector=localStorage.getItem('dk_inspector')||'';current.savedAt=new Date().toISOString();records=[...records.filter(x=>x.id!==current.id),JSON.parse(JSON.stringify(current))];saveLocal();renderDashboard();renderHistory();if($('reportRefresh'))$('reportRefresh').onclick=()=>{renderProfessionalReport();generateTraceabilityQR()};if($('reportPrint'))$('reportPrint').onclick=()=>window.print();$('reportId').textContent='Saved: '+current.id+' • '+current.result;alert('Inspection saved: '+current.id)}
function renderAll(){normalizeVisualRecords();fillDrawingFields();fillMeasurementMeta();fillApproval();renderDrawingChecks();renderDimensions();renderProcesses();renderVisual();renderPhotos();renderDefects();renderReview();renderDashboard()}
function renderDashboard(){if(current?.processes)processes.forEach(p=>current.processes[p]=processRecord(p));const c={PASS:0,REJECT:0,HOLD:0};records.forEach(x=>c[x.result]=(c[x.result]||0)+1);$('sTotal').textContent=records.length;$('sPass').textContent=c.PASS;$('sReject').textContent=c.REJECT;$('sHold').textContent=c.HOLD;$('currentSummary').innerHTML=current?'<b>'+esc(current.id)+'</b><br>'+esc(current.part.partName||'Part not identified')+'<br>'+esc(current.part.barcode||'No barcode'):'No inspection started.'}
function renderHistory(){const q=($('historySearch')?.value||'').toLowerCase();const list=records.filter(x=>JSON.stringify(x).toLowerCase().includes(q)).slice().reverse();$('historyList').innerHTML=list.map(x=>'<div class="history-card"><div><b>'+esc(x.id)+'</b> <span class="'+x.result.toLowerCase()+'">'+x.result+'</span><br>'+esc(x.part.project||'')+' • '+esc(x.part.partName||'')+' • '+esc(x.part.barcode||'')+'<br><small>'+new Date(x.savedAt||x.createdAt).toLocaleString()+'</small></div><button class="secondary" data-open="'+esc(x.id)+'">Open</button></div>').join('')||'<div class="muted">No records.</div>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{current=records.find(x=>x.id===b.dataset.open);fillIdentify();renderAll();nav('review')})}
function exportJson(){const blob=new Blob([JSON.stringify(records,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='quality-inspections-backup.json';a.click();URL.revokeObjectURL(a.href)}

// ===== Phase 7: Dashboard / History / Analytics =====
function phase7Filtered(){
 const q=($('historySearch')?.value||'').trim().toLowerCase(),st=$('historyStatus')?.value||'',u=($('historyUnit')?.value||'').trim().toLowerCase(),ins=($('historyInspector')?.value||'').trim().toLowerCase(),from=$('historyFrom')?.value||'',to=$('historyTo')?.value||'';
 return records.filter(x=>{const hay=[x.id,x.part?.project,x.part?.partNumber,x.part?.partName,x.part?.barcode,x.drawing?.drawingNumber,x.drawing?.revision,x.part?.unit,x.inspector].join(' ').toLowerCase();const d=String(x.savedAt||x.createdAt||'').slice(0,10);return (!q||hay.includes(q))&&(!st||(x.result||'HOLD')===st)&&(!u||String(x.part?.unit||'').toLowerCase().includes(u))&&(!ins||String(x.inspector||'').toLowerCase().includes(ins))&&(!from||d>=from)&&(!to||d<=to)}).sort((a,b)=>new Date(b.savedAt||b.createdAt)-new Date(a.savedAt||a.createdAt));
}
function renderDashboard(){
 const c={PASS:0,REJECT:0,HOLD:0},months={},open=records.reduce((n,x)=>n+(x.defects||[]).filter(d=>d.status==='OPEN').length,0);
 records.forEach(x=>{c[x.result||'HOLD']=(c[x.result||'HOLD']||0)+1;const d=new Date(x.savedAt||x.createdAt);if(!Number.isNaN(d.getTime())){const k=d.toISOString().slice(0,7);months[k]=(months[k]||0)+1}});
 $('sTotal').textContent=records.length;$('sPass').textContent=c.PASS;$('sReject').textContent=c.REJECT;$('sHold').textContent=c.HOLD;
 if($('sPassRate'))$('sPassRate').textContent=(records.length?Math.round(c.PASS/records.length*100):0)+'%';
 if($('sOpenDefects'))$('sOpenDefects').textContent=open;
 const total=records.length||1;
 if($('statusAnalytics'))$('statusAnalytics').innerHTML=[['PASS',c.PASS,'pass'],['REJECT',c.REJECT,'reject'],['HOLD',c.HOLD,'hold']].map(x=>'<div class="analytics-row"><span>'+x[0]+'</span><div class="bar"><i class="'+x[2]+'" style="width:'+Math.round(x[1]/total*100)+'%"></i></div><b>'+x[1]+'</b></div>').join('');
 const recent=records.slice().sort((a,b)=>new Date(b.savedAt||b.createdAt)-new Date(a.savedAt||a.createdAt)).slice(0,5);
 if($('recentInspections'))$('recentInspections').innerHTML=recent.map(x=>'<div class="recent-item"><b>'+esc(x.id)+'</b><span>'+esc(x.part?.partName||'')+' • '+esc(x.result||'HOLD')+'</span></div>').join('')||'<span class="muted">No saved inspections.</span>';
 const trend=Object.entries(months).sort().slice(-6),mx=Math.max(1,...trend.map(x=>x[1]));
 if($('trendAnalytics'))$('trendAnalytics').innerHTML=trend.map(x=>'<div class="trend-row"><span>'+x[0]+'</span><div class="bar"><i style="width:'+Math.round(x[1]/mx*100)+'%"></i></div><b>'+x[1]+'</b></div>').join('')||'<span class="muted">No trend data.</span>';
 if($('currentSummary'))$('currentSummary').innerHTML=current?'<b>'+esc(current.id)+'</b><br>'+esc(current.part.partName||'Part not identified')+'<br>'+esc(current.part.barcode||'No barcode'):'No inspection started.';
}
function renderHistory(){
 const list=phase7Filtered();if($('historyCount'))$('historyCount').textContent=list.length+' records';
 const old=$('historyList');if(old)old.innerHTML=list.map(x=>'<div class="history-card"><div><b>'+esc(x.id)+'</b> <span class="result-mini '+String(x.result||'HOLD').toLowerCase()+'">'+esc(x.result||'HOLD')+'</span><br>'+esc(x.part?.project||'')+' • '+esc(x.part?.partName||'')+' • '+esc(x.part?.barcode||'')+'<br><small>'+new Date(x.savedAt||x.createdAt).toLocaleString()+'</small></div><button class="secondary" data-open="'+esc(x.id)+'">Open</button></div>').join('')||'<div class="muted">No matching records.</div>';
 document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{current=records.find(x=>x.id===b.dataset.open);fillIdentify();renderAll();nav('review')});
}
function clearHistoryFilters(){['historySearch','historyStatus','historyUnit','historyInspector','historyFrom','historyTo'].forEach(id=>{if($(id))$(id).value=''});renderHistory()}
function exportHistoryCsv(){
 const list=phase7Filtered();if(!list.length){alert('No filtered records to export.');return}
 const h=['Inspection ID','Date','Project','Part Number','Part Name','Barcode','Drawing','Revision','Unit','Inspector','Result','Final Decision','Open Defects'];
 const rows=list.map(x=>[x.id,String(x.savedAt||x.createdAt).slice(0,10),x.part?.project||'',x.part?.partNumber||'',x.part?.partName||'',x.part?.barcode||'',x.drawing?.drawingNumber||'',x.drawing?.revision||'',x.part?.unit||'',x.inspector||'',x.result||'HOLD',x.approval?.decision||'',(x.defects||[]).filter(d=>d.status==='OPEN').length]);
 const csv=[h,...rows].map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='quality-inspection-history.csv';a.click();URL.revokeObjectURL(a.href);
}
function init(){
 ['project','partNumber','partName','barcode','drawingNumber','drawingRevision'].forEach(k=>$(k).addEventListener('input',updateIdentityGate));
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>nav(b.dataset.tab));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));
 $('loginBtn').onclick=()=>{const n=$('loginName').value.trim();if(!n)return alert('Inspector name required');localStorage.setItem('dk_inspector',n);$('login').classList.add('hidden');$('app').classList.remove('hidden');startNew()};
 $('newInspection').onclick=startNew;$('parseSticker').onclick=parseSticker;$('nativeScan').onclick=()=>{if(window.Android?.startNativeScanner)window.Android.startNativeScanner();else alert('Android scanner bridge available only in the Android build. Use manual sticker data here.')};
 $('drawingFile').onchange=loadDrawing;['drawingProject','drawingPartNumber','drawingDrawingNumber','drawingRevision','drawingNotes','drawingExtractedText'].forEach(k=>$(k).addEventListener('input',syncDrawingFields));$('extractDrawing').onclick=extractDrawingText;$('clearDrawing').onclick=clearDrawing;$('buildCharacteristics').onclick=buildCharacteristicsFromVerifiedText;$('addCharacteristic').onclick=addDimension;['measurementInstrument','calibrationNo','measurementMethod','measurementRemark'].forEach(k=>$(k).addEventListener('input',syncMeasurementMeta));$('markDrawingHold').onclick=()=>{current.drawing.manual=true;renderDrawingChecks()};$('addDefect').onclick=addDefect;$('photoFile').onchange=addPhoto;$('saveInspection').onclick=saveInspection;$('printReport').onclick=()=>window.print();['reportNo','inspectionDate','qualityEngineer','approvalDecision','approvalRemark'].forEach(k=>$(k)?.addEventListener('input',syncApproval));$('exportJson').onclick=exportJson;
 ['historySearch','historyStatus','historyUnit','historyInspector','historyFrom','historyTo'].forEach(id=>$(id)?.addEventListener('input',renderHistory));$('clearHistoryFilters').onclick=clearHistoryFilters;$('exportCsv').onclick=exportHistoryCsv;
 renderDashboard();renderHistory();renderProfessionalReport();generateTraceabilityQR();$('traceabilityScan')?.addEventListener('click',startTraceabilityScan);$('traceabilityLookup')?.addEventListener('click',()=>renderTraceabilityResult());$('traceabilityInput')?.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')renderTraceabilityResult()});
}

function validateBackupRecords(data){if(!Array.isArray(data))return{ok:false,records:[],message:'Backup must contain an inspection record array.'};const clean=data.filter(x=>x&&typeof x==='object'&&typeof x.id==='string');if(!clean.length)return{ok:false,records:[],message:'No valid inspection records found in backup.'};const ids=new Set();const unique=clean.filter(x=>{if(ids.has(x.id))return false;ids.add(x.id);return true});return{ok:true,records:unique,message:unique.length+' valid inspection record(s) found.'}}
function importJsonBackup(e){const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);const v=validateBackupRecords(data);if(!v.ok){alert(v.message);return}const existing=new Map(records.map(x=>[x.id,x]));v.records.forEach(x=>existing.set(x.id,x));records=Array.from(existing.values());saveLocal();renderDashboard();renderHistory();renderProfessionalReport();if($('backupStatus'))$('backupStatus').textContent=v.records.length+' record(s) restored/updated successfully.';alert(v.message+' Local history updated.')}catch(err){if($('backupStatus'))$('backupStatus').textContent='Invalid JSON backup.';alert('Invalid JSON backup file.')}};reader.readAsText(f);e.target.value=''}

function reportText(v){return esc(v==null||v===''?'—':String(v))}
function buildTraceabilityPayload(){const p=current?.part||{},d=current?.drawing||{};return JSON.stringify({inspectionId:current?.id||'',project:p.project||'',partNumber:p.partNumber||'',barcode:p.barcode||'',drawing:d.drawingNumber||'',revision:d.revision||''})}function generateTraceabilityQR(){if(!current)return;const box=$('inspectionQr');if(!box)return;box.innerHTML='';const payload=buildTraceabilityPayload();current.traceability=current.traceability||{};current.traceability.qrPayload=payload;current.traceability.generatedAt=new Date().toISOString();if(window.QRCode)new QRCode(box,{text:payload,width:180,height:180});else box.textContent='QR library unavailable. Payload: '+payload;if($('qrPayload'))$('qrPayload').value=payload}function renderProfessionalReport(){
 const x=current;if(!x)return;const a=x.approval||{},p=x.part||{},d=x.drawing||{};
 const set=(id,v)=>{if($(id))$(id).textContent=v};
 set('rReportNo','Report No: '+(a.reportNo||x.id||'—'));if($('qrPayload'))$('qrPayload').value=x.traceability?.qrPayload||buildTraceabilityPayload();set('rInspectionId',x.id);set('rDate',a.inspectionDate);set('rProject',p.project);set('rUnit',p.unit);set('rPart',p.partNumber);set('rPartName',p.partName);set('rDrawing',d.drawingNumber);set('rRevision',d.revision);set('rBarcode',p.barcode);set('rInspector',x.inspector);
 const status=x.result||finalStatus();const decision=a.decision||status;set('rDecision',decision);$('rDecision').className='report-status '+String(decision).toLowerCase();
 const pass=(x.dimensions||[]).filter(q=>dimResult(q)==='PASS').length,reject=(x.dimensions||[]).filter(q=>dimResult(q)==='REJECT').length,hold=(x.dimensions||[]).filter(q=>dimResult(q)==='HOLD').length,open=(x.defects||[]).filter(q=>q.status==='OPEN').length;
 $('rSummary').innerHTML='<div><b>System Result</b><span>'+reportText(status)+'</span></div><div><b>Dimensions</b><span>'+pass+' PASS / '+reject+' REJECT / '+hold+' HOLD</span></div><div><b>Open Defects</b><span>'+open+'</span></div><div><b>Process Count</b><span>'+processes.length+'</span></div>';
 $('rDimensions').innerHTML=(x.dimensions||[]).map(q=>{const z=measurementRange(q);return '<tr><td>'+reportText(q.name)+'</td><td>'+reportText(q.nominal)+'</td><td>± '+reportText(q.tol)+'</td><td>'+reportText(z.low)+'</td><td>'+reportText(z.high)+'</td><td>'+reportText(q.actual)+'</td><td>'+reportText(q.unit)+'</td><td>'+reportText(dimResult(q))+'</td></tr>'}).join('')||'<tr><td colspan="8">No characteristics recorded.</td></tr>';
 $('rProcesses').innerHTML=processes.map(name=>{const q=processRecord(name);return '<tr><td>'+reportText(name)+'</td><td>'+reportText(q.status)+'</td><td>'+reportText(q.operator)+'</td><td>'+reportText(q.date)+'</td><td>'+reportText(q.machine)+'</td><td>'+reportText(q.batch)+'</td><td>'+reportText(q.remark)+'</td></tr>'}).join('');
 $('rVisual').innerHTML=visual.map(name=>{const q=visualRecord(name);return '<div class="report-line"><b>'+reportText(name)+'</b><span>'+reportText(q.status)+'</span><small>'+reportText(q.inspector)+' • '+reportText(q.date)+' • '+reportText(q.remark)+'</small></div>'}).join('')||'<div class="muted">No visual records.</div>';
 $('rDefects').innerHTML=(x.defects||[]).map(q=>'<div class="report-line"><b>'+reportText(q.id)+' • '+reportText(q.type||'Defect')+'</b><span>'+reportText(q.status)+'</span><small>Reported by '+reportText(q.reportedBy)+' • '+reportText(q.reportedAt)+' • Rework: '+reportText(q.rework?.status)+' • '+reportText(q.rework?.action)+' • '+reportText(q.rework?.by)+' • '+reportText(q.rework?.date)+'</small></div>').join('')||'<div class="muted">No defects recorded.</div>';
 set('rSystemResult',status);set('rEngineer',a.qualityEngineer);set('rApprovedAt',a.approvedAt?new Date(a.approvedAt).toLocaleString():'—');set('rRemark',a.remark||x.remark);set('rAuditCreated',x.audit?.createdAt?new Date(x.audit.createdAt).toLocaleString():'—');set('rAuditUpdated',x.audit?.updatedAt?new Date(x.audit.updatedAt).toLocaleString():'—');set('rAuditBy',x.audit?.updatedBy||x.audit?.createdBy||'—');if($('rEvidence'))$('rEvidence').innerHTML=(x.photos||[]).map(q=>'<div class="report-evidence"><div><b>'+reportText(q.id)+'</b> • '+reportText(q.category)+'</div><small>'+reportText(q.name)+' • '+reportText(q.inspector)+' • '+reportText(q.addedAt)+'</small><img src="'+q.data+'"></div>').join('')||'<div class="muted">No photo evidence recorded.</div>';
}


window.DKQualityInspection = window.DKQualityInspection || {};
window.DKQualityInspection.getRecords = () => JSON.parse(JSON.stringify(records));
window.DKQualityInspection.replaceRecords = (next) => {
  if(!Array.isArray(next)) return false;
  records = next.filter(x=>x && typeof x==='object' && typeof x.id==='string');
  saveLocal();
  renderDashboard();
  renderHistory();
  renderProfessionalReport();
  if(current) renderAll();
  return true;
};
window.DKQualityInspection.refreshCloudViews = () => { renderDashboard(); renderHistory(); renderProfessionalReport(); };
init();})();