(()=>{'use strict';
const $=id=>document.getElementById(id),KEY='dk_quality_inspections_v1';
let records=JSON.parse(localStorage.getItem(KEY)||'[]'),current=null;
const processes=['Cutting','Punching','Milling','Welding','Grinding','Cleaning','Lacquering / Surface Treatment','Final Inspection'];
const visual=['Cutting size/straightness/burr','All required punching holes and positions','Milling complete, size and surface acceptable','Welding complete, position, porosity/crack/lump','Grinding complete, sharp edges removed','Stiffener type/position/quantity/gap/welding','End Cap / Rail / other components','Final visual inspection and sticker readability'];
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fresh(){return{id:'INS-'+Date.now().toString(36).toUpperCase(),createdAt:new Date().toISOString(),inspector:$('inspector')?.value||localStorage.getItem('dk_inspector')||'',part:{},drawing:{fileName:'',manual:false},dimensions:[],processes:Object.fromEntries(processes.map(x=>[x,'NOT COMPLETED'])),visual:Object.fromEntries(visual.map(x=>[x,'HOLD'])),photos:[],defects:[],result:'HOLD',remark:''}}
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(records));$('saveState').textContent='SAVED LOCALLY'}
function nav(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));if(id==='review')renderReview();if(id==='history')renderHistory();window.scrollTo(0,0)}
function init(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>nav(b.dataset.tab));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));$('loginBtn').onclick=()=>{const n=$('loginName').value.trim();if(!n)return alert('Inspector name required');localStorage.setItem('dk_inspector',n);$('login').classList.add('hidden');$('app').classList.remove('hidden');startNew();};$('newInspection').onclick=startNew;$('parseSticker').onclick=parseSticker;$('nativeScan').onclick=()=>{if(window.Android?.startNativeScanner)window.Android.startNativeScanner();else alert('Android scanner bridge available only in the Android build. Use manual sticker data here.');};$('drawingFile').onchange=loadDrawing;$('addCharacteristic').onclick=addDimension;$('markDrawingHold').onclick=()=>{current.drawing.manual=true;renderDrawingChecks()};$('addDefect').onclick=addDefect;$('photoFile').onchange=addPhoto;$('saveInspection').onclick=saveInspection;$('printReport').onclick=()=>window.print();$('exportJson').onclick=exportJson;$('historySearch').oninput=renderHistory;renderDashboard()}
function startNew(){current=fresh();current.inspector=localStorage.getItem('dk_inspector')||'';fillIdentify();renderAll();nav('identify')}
function fillIdentify(){const p=current.part;['project','partNumber','partName','barcode','drawingNumber','drawingRevision','unit','inspector'].forEach(k=>$(k).value=p[k]||current[k]||'');}
function parseSticker(){try{const d=window.DKStickerParser.parseSticker($('stickerRaw').value);current.part={project:d.project,partNumber:d.ipo,partName:d.partName,barcode:d.barcode,drawingNumber:'',drawingRevision:'',unit:d.unit,stickerCompany:d.stickerCompany,width:d.width,length:d.length};fillIdentify();if(!current.dimensions.length){current.dimensions=[{id:'DIM-01',name:'Overall Length',nominal:d.length,tol:1,actual:'',unit:'mm',remark:''},{id:'DIM-02',name:'Overall Width',nominal:d.width,tol:1,actual:'',unit:'mm',remark:''}]};renderAll();alert('Sticker parsed. Verify Project/Part/Drawing before continuing.')}catch(e){alert(e.message)}}
function loadDrawing(e){const f=e.target.files[0];if(!f)return;current.drawing.fileName=f.name;const url=URL.createObjectURL(f);$('drawingMeta').textContent=f.name+' • '+Math.round(f.size/1024)+' KB';$('drawingPreview').innerHTML=f.type==='application/pdf'?'<iframe src="'+url+'"></iframe>':'<img src="'+url+'" alt="drawing">';renderDrawingChecks()}
function renderDrawingChecks(){$('drawingChecks').innerHTML=['Drawing Number verified','Revision verified','Project/Part mapping verified','Dimensions and tolerances readable'].map((x,i)=>'<label class="check-item"><span>'+x+'</span><select data-dc="'+i+'"><option>PASS</option><option>HOLD</option></select></label>').join('')+'<div class="muted" style="padding:10px">If a dimension/tolerance cannot be reliably read, select HOLD and perform manual verification.</div>'}
function addDimension(){current.dimensions.push({id:'DIM-'+String(current.dimensions.length+1).padStart(2,'0'),name:'New Characteristic',nominal:'',tol:'',actual:'',unit:'mm',remark:''});renderDimensions()}
function dimResult(d){if(d.actual===''||d.nominal===''||d.tol==='')return'HOLD';const a=Number(d.actual),n=Number(d.nominal),t=Math.abs(Number(d.tol));return Number.isFinite(a)&&a>=n-t&&a<=n+t?'PASS':'REJECT'}
function renderDimensions(){ $('dimensionBody').innerHTML=current.dimensions.map((d,i)=>'<tr><td>'+esc(d.id)+'</td><td><input data-d="'+i+'" data-k="name" value="'+esc(d.name)+'"></td><td><input type="number" data-d="'+i+'" data-k="nominal" value="'+esc(d.nominal)+'"></td><td><input type="number" data-d="'+i+'" data-k="tol" value="'+esc(d.tol)+'"></td><td><input type="number" data-d="'+i+'" data-k="actual" value="'+esc(d.actual)+'"></td><td><input data-d="'+i+'" data-k="unit" value="'+esc(d.unit)+'"></td><td class="'+dimResult(d).toLowerCase()+'">'+dimResult(d)+'</td><td><input data-d="'+i+'" data-k="remark" value="'+esc(d.remark)+'"></td><td><button class="danger" data-del="'+i+'">×</button></td></tr>').join('');document.querySelectorAll('[data-d]').forEach(x=>x.onchange=()=>{current.dimensions[+x.dataset.d][x.dataset.k]=x.value;renderDimensions();renderReview()});document.querySelectorAll('[data-del]').forEach(x=>x.onclick=()=>{current.dimensions.splice(+x.dataset.del,1);renderDimensions();renderReview()});const rs=current.dimensions.map(dimResult);$('dimensionResult').textContent=rs.includes('REJECT')?'REJECT':rs.includes('HOLD')?'HOLD':'PASS'}
function renderProcesses(){$('processBody').innerHTML=processes.map(p=>'<div class="process-item"><span><b>'+p+'</b><br><small class="muted">Mandatory process verification</small></span><select class="status-select" data-proc="'+esc(p)+'"><option>COMPLETED</option><option>NOT COMPLETED</option><option>NOT APPLICABLE</option><option>HOLD</option></select></div>').join('');document.querySelectorAll('[data-proc]').forEach(x=>{x.value=current.processes[x.dataset.proc]||'NOT COMPLETED';x.onchange=()=>{current.processes[x.dataset.proc]=x.value;renderReview()}})}
function renderVisual(){$('visualBody').innerHTML=visual.map((v,i)=>'<div class="visual-item"><span>'+esc(v)+'</span><select data-vis="'+i+'"><option>PASS</option><option>FAIL</option><option>HOLD</option><option>NOT APPLICABLE</option></select></div>').join('');document.querySelectorAll('[data-vis]').forEach(x=>{x.value=current.visual[visual[+x.dataset.vis]]||'HOLD';x.onchange=()=>{current.visual[visual[+x.dataset.vis]]=x.value;renderReview()}})}
function addPhoto(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{current.photos.push({category:$('photoCategory').value,name:f.name,data:r.result});renderPhotos()};r.readAsDataURL(f);e.target.value=''}
function renderPhotos(){$('photoList').innerHTML=current.photos.map((p,i)=>'<div class="photo-card"><b>'+esc(p.category)+'</b> — '+esc(p.name)+'<br><img src="'+p.data+'"></div>').join('')||'<div class="muted">No photos yet.</div>'}
function addDefect(){const type=$('defectType').value.trim();if(!type)return alert('Defect type required');current.defects.push({id:'DEF-'+Date.now().toString(36).toUpperCase(),process:$('defectProcess').value,type,actual:$('defectActual').value,remark:$('defectRemark').value,status:'OPEN'});$('defectType').value='';$('defectActual').value='';$('defectRemark').value='';renderDefects();renderReview()}
function renderDefects(){$('defectList').innerHTML=current.defects.map((d,i)=>'<div class="defect-card"><b>'+esc(d.id)+' • '+esc(d.type)+'</b><br><span>'+esc(d.process)+' — '+esc(d.status)+'</span><br>'+esc(d.actual)+'<br><small>'+esc(d.remark)+'</small><button class="danger" data-close="'+i+'">Close after rework</button></div>').join('')||'<div class="muted">No defects.</div>';document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>{current.defects[+x.dataset.close].status='RECHECK';renderDefects();renderReview()})}
function gates(){const dims=current.dimensions.map(dimResult);const proc=processes.every(p=>['COMPLETED','NOT APPLICABLE'].includes(current.processes[p]));const vis=visual.every(v=>['PASS','NOT APPLICABLE'].includes(current.visual[v]));const mismatch=!$('mismatch')?.classList.contains('hidden');const drawingHold=current.drawing.manual;const criticalDef=current.defects.some(d=>d.status==='OPEN');return[{name:'Part ↔ Drawing identity verified',ok:!mismatch&&!drawingHold},{name:'Mandatory processes completed',ok:proc},{name:'Dimensions within tolerance',ok:dims.length>0&&!dims.includes('REJECT')&&!dims.includes('HOLD')},{name:'Manual / visual inspection passed',ok:vis},{name:'No open critical defect',ok:!criticalDef},{name:'Final inspection completed',ok:true}]}
function finalStatus(){const g=gates();if(g.some(x=>x.name.includes('identity')&&x.ok===false)||g.some(x=>x.name.includes('Dimensions')&&x.ok===false&&current.dimensions.some(d=>dimResult(d)==='REJECT')))return'REJECT';if(g.every(x=>x.ok))return'PASS';return'HOLD'}
function renderReview(){const g=gates();$('gateChecks').innerHTML=g.map(x=>'<div class="check-item"><span>'+x.name+'</span><b class="'+(x.ok?'ok':'hold')+'">'+(x.ok?'PASS':'HOLD')+'</b></div>').join('');const s=finalStatus();$('finalResult').textContent=s;$('finalResult').className='result '+s.toLowerCase();$('reportId').textContent=current.savedAt?'Inspection ID: '+current.id:''}
function saveInspection(){current.remark=$('finalRemark').value;current.result=finalStatus();current.inspector=localStorage.getItem('dk_inspector')||'';current.savedAt=new Date().toISOString();records=[...records.filter(x=>x.id!==current.id),JSON.parse(JSON.stringify(current))];saveLocal();renderDashboard();renderHistory();$('reportId').textContent='Saved: '+current.id+' • '+current.result;alert('Inspection saved: '+current.id)}
function renderAll(){renderDrawingChecks();renderDimensions();renderProcesses();renderVisual();renderPhotos();renderDefects();renderReview();renderDashboard()}
function renderDashboard(){const c={PASS:0,REJECT:0,HOLD:0};records.forEach(x=>c[x.result]=(c[x.result]||0)+1);$('sTotal').textContent=records.length;$('sPass').textContent=c.PASS;$('sReject').textContent=c.REJECT;$('sHold').textContent=c.HOLD;$('currentSummary').innerHTML=current?'<b>'+esc(current.id)+'</b><br>'+esc(current.part.partName||'Part not identified')+'<br>'+esc(current.part.barcode||'No barcode'):'No inspection started.'}
function renderHistory(){const q=($('historySearch')?.value||'').toLowerCase();const list=records.filter(x=>JSON.stringify(x).toLowerCase().includes(q)).slice().reverse();$('historyList').innerHTML=list.map(x=>'<div class="history-card"><div><b>'+esc(x.id)+'</b> <span class="'+x.result.toLowerCase()+'">'+x.result+'</span><br>'+esc(x.part.project||'')+' • '+esc(x.part.partName||'')+' • '+esc(x.part.barcode||'')+'<br><small>'+new Date(x.savedAt||x.createdAt).toLocaleString()+'</small></div><button class="secondary" data-open="'+esc(x.id)+'">Open</button></div>').join('')||'<div class="muted">No records.</div>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{current=records.find(x=>x.id===b.dataset.open);fillIdentify();renderAll();nav('review')})}
function exportJson(){const blob=new Blob([JSON.stringify(records,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='quality-inspections-backup.json';a.click();URL.revokeObjectURL(a.href)}
init();})();