(()=>{'use strict';
const $=id=>document.getElementById(id),KEY='dk_quality_inspections_v1';
let records=JSON.parse(localStorage.getItem(KEY)||'[]'),current=null;let drawingObjectUrl='';
const processes=['Cutting','Punching','Milling','Welding','Grinding','Cleaning','Lacquering / Surface Treatment','Final Inspection'];
const visual=['Cutting size/straightness/burr','All required punching holes and positions','Milling complete, size and surface acceptable','Welding complete, position, porosity/crack/lump','Grinding complete, sharp edges removed','Stiffener type/position/quantity/gap/welding','End Cap / Rail / other components','Final visual inspection and sticker readability'];
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fresh(){return{id:'INS-'+Date.now().toString(36).toUpperCase(),createdAt:new Date().toISOString(),inspector:$('inspector')?.value||localStorage.getItem('dk_inspector')||'',part:{},drawing:{fileName:'',manual:false,checks:[],status:'NOT UPLOADED',fileType:'',fileSize:0,project:'',partNumber:'',drawingNumber:'',revision:'',extraction:'NOT ATTEMPTED',extractedText:'',notes:''},measurement:{instrument:'',calibrationNo:'',method:'',remark:''},dimensions:[],processes:Object.fromEntries(processes.map(x=>[x,{status:'NOT COMPLETED',operator:'',date:'',machine:'',batch:'',remark:''}])),visual:Object.fromEntries(visual.map(x=>[x,{status:'HOLD',inspector:'',date:'',remark:''}])),photos:[],defects:[],result:'HOLD',remark:''}}
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(records));$('saveState').textContent='SAVED LOCALLY'}
function nav(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));if(id==='review')renderReview();if(id==='history')renderHistory();window.scrollTo(0,0)}
function init(){['project','partNumber','partName','barcode','drawingNumber','drawingRevision'].forEach(k=>$(k).addEventListener('input',updateIdentityGate));document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>nav(b.dataset.tab));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go));$('loginBtn').onclick=()=>{const n=$('loginName').value.trim();if(!n)return alert('Inspector name required');localStorage.setItem('dk_inspector',n);$('login').classList.add('hidden');$('app').classList.remove('hidden');startNew();};$('newInspection').onclick=startNew;$('parseSticker').onclick=parseSticker;$('nativeScan').onclick=()=>{if(window.Android?.startNativeScanner)window.Android.startNativeScanner();else alert('Android scanner bridge available only in the Android build. Use manual sticker data here.');};$('drawingFile').onchange=loadDrawing;['drawingProject','drawingPartNumber','drawingDrawingNumber','drawingRevision','drawingNotes','drawingExtractedText'].forEach(k=>$(k).addEventListener('input',syncDrawingFields));$('extractDrawing').onclick=extractDrawingText;$('clearDrawing').onclick=clearDrawing;$('buildCharacteristics').onclick=buildCharacteristicsFromVerifiedText;$('addCharacteristic').onclick=addDimension;['measurementInstrument','calibrationNo','measurementMethod','measurementRemark'].forEach(k=>$(k).addEventListener('input',syncMeasurementMeta));$('markDrawingHold').onclick=()=>{current.drawing.manual=true;renderDrawingChecks()};$('addDefect').onclick=addDefect;$('photoFile').onchange=addPhoto;$('saveInspection').onclick=saveInspection;$('printReport').onclick=()=>window.print();$('exportJson').onclick=exportJson;$('historySearch').oninput=renderHistory;renderDashboard()}
function startNew(){current=fresh();current.inspector=localStorage.getItem('dk_inspector')||'';fillIdentify();renderAll();nav('identify')}
function fillIdentify(){const p=current.part;['project','partNumber','partName','barcode','drawingNumber','drawingRevision','unit','inspector'].forEach(k=>$(k).value=p[k]||current[k]||'');updateIdentityGate()}
function updateIdentityGate(){const required=['project','partNumber','partName','barcode','drawingNumber','drawingRevision'];const missing=required.filter(k=>!$(k).value.trim());const el=$('identityGate');el.classList.remove('hidden');if(missing.length){el.classList.remove('ready');el.textContent='⛔ INSPECTION LOCKED — Missing: '+missing.join(', ')+'. Verify Part ↔ Project ↔ Drawing ↔ Revision before continuing.'}else{el.classList.add('ready');el.textContent='✓ IDENTITY VERIFIED — Part ↔ Project ↔ Drawing ↔ Revision ready for inspection.'}}

function parseSticker(){try{const d=window.DKStickerParser.parseSticker($('stickerRaw').value);current.part={project:d.project,partNumber:d.ipo,partName:d.partName,barcode:d.barcode,drawingNumber:'',drawingRevision:'',unit:d.unit,stickerCompany:d.stickerCompany,width:d.width,length:d.length};fillIdentify();if(!current.dimensions.length){current.dimensions=[{id:'DIM-01',name:'Overall Length',nominal:d.length,tol:1,actual:'',unit:'mm',remark:''},{id:'DIM-02',name:'Overall Width',nominal:d.width,tol:1,actual:'',unit:'mm',remark:''}]};renderAll();alert('Sticker parsed. Verify Project/Part/Drawing before continuing.')}catch(e){alert(e.message)}}
function syncDrawingFields(){if(!current)return;current.drawing.project=$('drawingProject').value.trim();current.drawing.partNumber=$('drawingPartNumber').value.trim();current.drawing.drawingNumber=$('drawingDrawingNumber').value.trim();current.drawing.revision=$('drawingRevision').value.trim();current.drawing.notes=$('drawingNotes').value.trim();current.drawing.extractedText=$('drawingExtractedText').value;renderDrawingChecks();renderReview()}
function drawingMatchesIdentity(){const p=current.part||{};const d=current.drawing||{};return !!(p.project&&p.partNumber&&p.drawingNumber&&p.drawingRevision&&d.project&&d.partNumber&&d.drawingNumber&&d.revision&&d.project===p.project&&d.partNumber===p.partNumber&&d.drawingNumber===p.drawingNumber&&d.revision===p.drawingRevision)}
function clearDrawing(){if(drawingObjectUrl)URL.revokeObjectURL(drawingObjectUrl);drawingObjectUrl='';current.drawing={fileName:'',manual:false,checks:[],status:'NOT UPLOADED',fileType:'',fileSize:0,project:'',partNumber:'',drawingNumber:'',revision:'',extraction:'NOT ATTEMPTED',extractedText:'',notes:''};$('drawingFile').value='';$('drawingMeta').textContent='No drawing uploaded.';$('drawingPreview').innerHTML='';fillDrawingFields();renderDrawingChecks();renderReview()}
function fillDrawingFields(){if(!current)return;[['drawingProject',current.drawing.project],['drawingPartNumber',current.drawing.partNumber],['drawingDrawingNumber',current.drawing.drawingNumber],['drawingRevision',current.drawing.revision],['drawingNotes',current.drawing.notes],['drawingExtractedText',current.drawing.extractedText]].forEach(([id,v])=>$(id).value=v||'')}
function loadDrawing(e){const f=e.target.files[0];if(!f)return;if(!/^application\/pdf$|^image\//.test(f.type)){alert('Only PDF or drawing image is allowed.');e.target.value='';return}if(drawingObjectUrl)URL.revokeObjectURL(drawingObjectUrl);drawingObjectUrl=URL.createObjectURL(f);current.drawing.fileName=f.name;current.drawing.fileType=f.type;current.drawing.fileSize=f.size;current.drawing.status='UPLOADED';current.drawing.extraction='NOT ATTEMPTED';$('drawingMeta').textContent=f.name+' • '+Math.max(1,Math.round(f.size/1024))+' KB • '+f.type;$('drawingPreview').innerHTML=f.type==='application/pdf'?'<iframe title="Approved drawing PDF" src="'+drawingObjectUrl+'"></iframe>':'<img src="'+drawingObjectUrl+'" alt="Approved engineering drawing">';fillDrawingFields();renderDrawingChecks();renderReview()}
async function extractDrawingText(){if(!current.drawing.fileName){alert('Upload the approved drawing first.');return}current.drawing.extraction='MANUAL VERIFICATION REQUIRED';current.drawing.manual=true;$('drawingExtractStatus').textContent='Manual Verification Required — browser-safe extraction is not being guessed.';renderDrawingChecks();renderReview()}

function renderDrawingChecks(){if(!current)return;const labels=['Drawing file uploaded','Drawing Number verified','Revision verified','Project/Part mapping verified','Dimensions/tolerances readable'];$('drawingChecks').innerHTML=labels.map((x,i)=>'<label class="check-item"><span>'+x+'</span><select data-dc="'+i+'"><option>PASS</option><option>HOLD</option></select></label>').join('');const values=[current.drawing.status==='UPLOADED'?'PASS':'HOLD',current.drawing.checks[1]||'HOLD',current.drawing.checks[2]||'HOLD',current.drawing.checks[3]||'HOLD',current.drawing.checks[4]||'HOLD'];document.querySelectorAll('[data-dc]').forEach(s=>{const i=+s.dataset.dc;s.value=values[i];s.disabled=i===0;s.onchange=()=>{current.drawing.checks[i]=s.value;renderReview()}});$('drawingExtractStatus').textContent=current.drawing.extraction==='NOT ATTEMPTED'?'Extraction status: Pending verification':current.drawing.extraction.replaceAll('_',' ')}
function syncMeasurementMeta(){if(!current)return;current.measurement={instrument:$('measurementInstrument').value.trim(),calibrationNo:$('calibrationNo').value.trim(),method:$('measurementMethod').value.trim(),remark:$('measurementRemark').value.trim()};renderReview()}
function fillMeasurementMeta(){if(!current||!current.measurement)return;[['measurementInstrument',current.measurement.instrument],['calibrationNo',current.measurement.calibrationNo],['measurementMethod',current.measurement.method],['measurementRemark',current.measurement.remark]].forEach(([id,v])=>$(id).value=v||'')}
function addDimension(seed){const d=seed||{id:'DIM-'+String(current.dimensions.length+1).padStart(2,'0'),name:'New Characteristic',type:'DIMENSION',reference:'',nominal:'',tol:'',actual:'',unit:'mm',remark:'',critical:false};current.dimensions.push(d);renderDimensions()}
function buildCharacteristicsFromVerifiedText(){const text=$('drawingExtractedText').value.trim();if(!text){alert('Enter verified drawing information first. Do not enter guessed values.');return}const lines=text.split(/\\n|\\r/).map(x=>x.trim()).filter(Boolean);const found=[];const re=/^(.+?)\\s*[:|=]\\s*(-?\\d+(?:\\.\\d+)?)\\s*(?:mm)?\\s*(?:±\\s*(\\d+(?:\\.\\d+)?))?\\s*(?:mm)?$/i;lines.forEach((line)=>{const m=line.match(re);if(m){found.push({name:m[1].trim(),type:'DIMENSION',reference:'Verified drawing text',nominal:m[2],tol:m[3]||'',actual:'',unit:'mm',remark:'',critical:false})}});if(!found.length){alert('No reliably structured dimension line found. Manual characteristic entry is required.');current.drawing.manual=true;current.drawing.extraction='MANUAL VERIFICATION REQUIRED';renderReview();return}found.forEach(x=>addDimension(x));current.drawing.extraction='VERIFIED DATA RECORDED';current.drawing.manual=false;renderDrawingChecks();renderReview();alert(found.length+' verified characteristic(s) added. Review each one before inspection.')}

function dimResult(d){if(d.actual===''||d.nominal===''||d.tol==='')return'HOLD';const a=Number(d.actual),n=Number(d.nominal),t=Math.abs(Number(d.tol));if(!Number.isFinite(a)||!Number.isFinite(n)||!Number.isFinite(t))return'HOLD';return a>=n-t&&a<=n+t?'PASS':'REJECT'}
function measurementRange(d){if(d.nominal===''||d.tol==='')return{low:'',high:''};const n=Number(d.nominal),t=Math.abs(Number(d.tol));if(!Number.isFinite(n)||!Number.isFinite(t))return{low:'',high:''};return{low:n-t,high:n+t}}
function measurementStats(){const total=current.dimensions.length,done=current.dimensions.filter(d=>d.actual!=='').length,critical=current.dimensions.filter(d=>d.critical).length,criticalDone=current.dimensions.filter(d=>d.critical&&d.actual!=='').length;return{total,done,critical,criticalDone}}
function renderDimensions(){ $('dimensionBody').innerHTML=current.dimensions.map((d,i)=>'<tr><td>'+esc(d.id)+'</td><td><input data-d="'+i+'" data-k="name" value="'+esc(d.name)+'"><select data-d="'+i+'" data-k="type"><option>DIMENSION</option><option>HOLE</option><option>MILLING</option><option>STIFFENER</option><option>POSITION</option><option>ANGLE</option><option>OTHER</option></select></td><td><input data-d="'+i+'" data-k="reference" value="'+esc(d.reference||'')+'" placeholder="Drawing ref"></td><td><input type="number" data-d="'+i+'" data-k="nominal" value="'+esc(d.nominal)+'"></td><td><input type="number" data-d="'+i+'" data-k="tol" value="'+esc(d.tol)+'"></td><td><input type="number" data-d="'+i+'" data-k="actual" value="'+esc(d.actual)+'"></td><td><input data-d="'+i+'" data-k="unit" value="'+esc(d.unit)+'"></td><td>'+esc(measurementRange(d).low===''?'—':measurementRange(d).low.toFixed(3))+'</td><td>'+esc(measurementRange(d).high===''?'—':measurementRange(d).high.toFixed(3))+'</td><td><label><input type="checkbox" data-d="'+i+'" data-k="critical" '+(d.critical?'checked':'')+'> Critical</label></td><td class="'+dimResult(d).toLowerCase()+'">'+dimResult(d)+'</td><td><input data-d="'+i+'" data-k="remark" value="'+esc(d.remark)+'"></td><td><button class="danger" data-del="'+i+'">×</button></td></tr>').join('');document.querySelectorAll('[data-d]').forEach(x=>x.onchange=()=>{current.dimensions[+x.dataset.d][x.dataset.k]=x.type==='checkbox'?x.checked:x.value;renderDimensions();renderReview()});document.querySelectorAll('[data-del]').forEach(x=>x.onclick=()=>{current.dimensions.splice(+x.dataset.del,1);renderDimensions();renderReview()});const rs=current.dimensions.map(dimResult);$('dimensionResult').textContent=rs.length===0?'PENDING':rs.includes('REJECT')?'REJECT':rs.includes('HOLD')?'HOLD':'PASS';const ms=measurementStats();if($('measurementProgress'))$('measurementProgress').textContent=ms.done+' / '+ms.total+' completed';if($('criticalSummary'))$('criticalSummary').textContent='Critical: '+ms.critical+' ('+ms.criticalDone+' measured)'}
function processRecord(p){
 const v=current.processes?.[p];
 if(v&&typeof v==='object')return{status:v.status||'NOT COMPLETED',operator:v.operator||'',date:v.date||'',machine:v.machine||'',batch:v.batch||'',remark:v.remark||''};
 return{status:v||'NOT COMPLETED',operator:'',date:'',machine:'',batch:'',remark:''};
}
function syncProcessField(p,k,value){if(!current)return;const v=processRecord(p);v[k]=value;current.processes[p]=v;renderReview()}
function renderProcesses(){
 $('processBody').innerHTML=processes.map((p,i)=>{const v=processRecord(p);return '<div class="process-card"><div class="process-head"><div><b>'+esc(p)+'</b><br><small class="muted">Mandatory process verification & traceability</small></div><select class="status-select" data-proc="'+esc(p)+'"><option>COMPLETED</option><option>NOT COMPLETED</option><option>NOT APPLICABLE</option><option>HOLD</option></select></div><div class="process-fields"><label>Operator / Employee<input data-pf="'+i+'" data-pk="operator" value="'+esc(v.operator)+'" placeholder="Name / ID"></label><label>Process Date<input type="date" data-pf="'+i+'" data-pk="date" value="'+esc(v.date)+'"></label><label>Machine / Line<input data-pf="'+i+'" data-pk="machine" value="'+esc(v.machine)+'" placeholder="Machine / Line"></label><label>Batch / Job / Lot<input data-pf="'+i+'" data-pk="batch" value="'+esc(v.batch)+'" placeholder="Batch / Job / Lot"></label><label class="wide">Process Remark<textarea data-pf="'+i+'" data-pk="remark" placeholder="Process result / handover remark">'+esc(v.remark)+'</textarea></label></div></div>'}).join('');
 document.querySelectorAll('[data-proc]').forEach(x=>{const p=x.dataset.proc;x.value=processRecord(p).status;x.onchange=()=>{syncProcessField(p,'status',x.value);renderProcesses()}});
 document.querySelectorAll('[data-pf]').forEach(x=>x.onchange=()=>{const p=processes[+x.dataset.pf];syncProcessField(p,x.dataset.pk,x.value)});
}

function visualRecord(v){
 const x=current.visual?.[v];
 if(x&&typeof x==='object')return{status:x.status||'HOLD',inspector:x.inspector||'',date:x.date||'',remark:x.remark||''};
 return{status:x||'HOLD',inspector:'',date:'',remark:''};
}
function syncVisualField(v,k,value){const x=visualRecord(v);x[k]=value;current.visual[v]=x;renderReview()}
function renderVisual(){
 $('visualBody').innerHTML=visual.map((v,i)=>{const x=visualRecord(v);return '<div class="visual-card"><div class="visual-head"><b>'+esc(v)+'</b><select data-vis="'+i+'"><option>PASS</option><option>FAIL</option><option>HOLD</option><option>NOT APPLICABLE</option></select></div><div class="visual-fields"><label>Inspector<input data-vf="'+i+'" data-vk="inspector" value="'+esc(x.inspector)+'" placeholder="Name / ID"></label><label>Inspection Date<input type="date" data-vf="'+i+'" data-vk="date" value="'+esc(x.date)+'"></label><label>Remark<textarea data-vf="'+i+'" data-vk="remark" placeholder="Observation / specification reference">'+esc(x.remark)+'</textarea></label></div></div>'}).join('');
 document.querySelectorAll('[data-vis]').forEach(x=>{const v=visual[+x.dataset.vis];x.value=visualRecord(v).status;x.onchange=()=>{syncVisualField(v,'status',x.value);renderVisual()}});
 document.querySelectorAll('[data-vf]').forEach(x=>x.onchange=()=>{const v=visual[+x.dataset.vf];syncVisualField(v,x.dataset.vk,x.value)});
}
function addPhoto(e){const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('image/')){alert('Only image evidence is allowed.');e.target.value='';return}const r=new FileReader();r.onload=()=>{current.photos.push({id:'PHOTO-'+Date.now().toString(36).toUpperCase(),category:$('photoCategory').value,name:f.name,data:r.result,addedAt:new Date().toISOString(),inspector:localStorage.getItem('dk_inspector')||''});renderPhotos()};r.readAsDataURL(f);e.target.value=''}
function renderPhotos(){$('photoList').innerHTML=current.photos.map((p,i)=>'<div class="photo-card"><b>'+esc(p.category)+'</b> — '+esc(p.name)+'<br><img src="'+p.data+'"></div>').join('')||'<div class="muted">No photos yet.</div>'}
function addDefect(){const type=$('defectType').value.trim();if(!type)return alert('Defect type required');current.defects.push({id:'DEF-'+Date.now().toString(36).toUpperCase(),process:$('defectProcess').value,type,actual:$('defectActual').value,remark:$('defectRemark').value,status:'OPEN'});$('defectType').value='';$('defectActual').value='';$('defectRemark').value='';renderDefects();renderReview()}
function renderDefects(){$('defectList').innerHTML=current.defects.map((d,i)=>'<div class="defect-card"><b>'+esc(d.id)+' • '+esc(d.type)+'</b><br><span>'+esc(d.process)+' — '+esc(d.status)+'</span><br>'+esc(d.actual)+'<br><small>Reported by: '+esc(d.reportedBy||'')+' • '+esc(d.reportedAt||'')+'</small><br><small>'+esc(d.remark)+'</small><div class="rework-fields"><label>Rework Action<input data-rw="'+i+'" data-rk="action" value="'+esc(d.rework?.action||'')" placeholder="Correction / rework action"></label><label>Rework By<input data-rw="'+i+'" data-rk="by" value="'+esc(d.rework?.by||'')" placeholder="Employee / operator"></label><label>Rework Date<input type="date" data-rw="'+i+'" data-rk="date" value="'+esc(d.rework?.date||'')"></label><label>Rework Remark<textarea data-rw="'+i+'" data-rk="remark">'+esc(d.rework?.remark||'')+'</textarea></label></div><button class="danger" data-close="'+i+'">Close after rework / recheck</button></div>').join('')||'<div class="muted">No defects.</div>';document.querySelectorAll('[data-rw]').forEach(x=>x.onchange=()=>{const d=current.defects[+x.dataset.rw];d.rework=d.rework||{status:'PENDING'};d.rework[x.dataset.rk]=x.value;renderReview()});document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>{const d=current.defects[+x.dataset.close];if(!d.rework?.action||!d.rework?.by||!d.rework?.date){alert('Complete rework action, person and date before recheck.');return}d.status='RECHECK';d.rework.status='COMPLETED';renderDefects();renderReview()})}
function gates(){updateIdentityGate();const dims=current.dimensions.map(dimResult);const measurementMetaOk=!!(current.measurement?.instrument&&current.measurement?.method);const proc=processes.every(p=>['COMPLETED','NOT APPLICABLE'].includes(processRecord(p).status));const trace=processes.every(p=>{const v=processRecord(p);return v.status==='NOT APPLICABLE'||(v.status==='COMPLETED'&&v.operator&&v.date&&v.machine&&v.batch)});const vis=visual.every(v=>['PASS','NOT APPLICABLE'].includes(visualRecord(v).status));const visualTrace=visual.every(v=>{const x=visualRecord(v);return x.status==='NOT APPLICABLE'||(x.status==='PASS'&&x.inspector&&x.date)});const mismatch=['project','partNumber','partName','barcode','drawingNumber','drawingRevision'].some(k=>!$(k).value.trim());const drawingHold=current.drawing.manual||current.drawing.status!=='UPLOADED'||current.drawing.checks.length<5||current.drawing.checks.some((x,i)=>i>0&&x!=='PASS')||current.drawing.extraction==='MANUAL VERIFICATION REQUIRED';const criticalDef=current.defects.some(d=>d.status==='OPEN');return[{name:'Part ↔ Drawing identity verified',ok:!mismatch&&!drawingHold},{name:'Mandatory processes completed',ok:proc},{name:'Process traceability complete',ok:trace},{name:'Measurement record complete',ok:measurementMetaOk},{name:'Dimensions within tolerance',ok:dims.length>0&&!dims.includes('REJECT')&&!dims.includes('HOLD')},{name:'Manual / visual inspection passed',ok:vis},{name:'Visual inspection traceability complete',ok:visualTrace},{name:'No open critical defect',ok:!criticalDef},{name:'Final inspection completed',ok:['COMPLETED','NOT APPLICABLE'].includes(processRecord('Final Inspection').status)}]}
function finalStatus(){const g=gates();if(current.dimensions.some(d=>dimResult(d)==='REJECT')||current.defects.some(d=>d.status==='OPEN'))return'REJECT';if(g.every(x=>x.ok))return'PASS';return'HOLD'}
function renderReview(){const g=gates();$('gateChecks').innerHTML=g.map(x=>'<div class="check-item"><span>'+x.name+'</span><b class="'+(x.ok?'ok':'hold')+'">'+(x.ok?'PASS':'HOLD')+'</b></div>').join('');const s=finalStatus();$('finalResult').textContent=s;$('finalResult').className='result '+s.toLowerCase();$('reportId').textContent=current.savedAt?'Inspection ID: '+current.id:''}
function saveInspection(){processes.forEach(p=>current.processes[p]=processRecord(p));current.remark=$('finalRemark').value;current.result=finalStatus();current.inspector=localStorage.getItem('dk_inspector')||'';current.savedAt=new Date().toISOString();records=[...records.filter(x=>x.id!==current.id),JSON.parse(JSON.stringify(current))];saveLocal();renderDashboard();renderHistory();$('reportId').textContent='Saved: '+current.id+' • '+current.result;alert('Inspection saved: '+current.id)}
function renderAll(){fillDrawingFields();fillMeasurementMeta();renderDrawingChecks();renderDimensions();renderProcesses();renderVisual();renderPhotos();renderDefects();renderReview();renderDashboard()}
function renderDashboard(){if(current?.processes)processes.forEach(p=>current.processes[p]=processRecord(p));const c={PASS:0,REJECT:0,HOLD:0};records.forEach(x=>c[x.result]=(c[x.result]||0)+1);$('sTotal').textContent=records.length;$('sPass').textContent=c.PASS;$('sReject').textContent=c.REJECT;$('sHold').textContent=c.HOLD;$('currentSummary').innerHTML=current?'<b>'+esc(current.id)+'</b><br>'+esc(current.part.partName||'Part not identified')+'<br>'+esc(current.part.barcode||'No barcode'):'No inspection started.'}
function renderHistory(){const q=($('historySearch')?.value||'').toLowerCase();const list=records.filter(x=>JSON.stringify(x).toLowerCase().includes(q)).slice().reverse();$('historyList').innerHTML=list.map(x=>'<div class="history-card"><div><b>'+esc(x.id)+'</b> <span class="'+x.result.toLowerCase()+'">'+x.result+'</span><br>'+esc(x.part.project||'')+' • '+esc(x.part.partName||'')+' • '+esc(x.part.barcode||'')+'<br><small>'+new Date(x.savedAt||x.createdAt).toLocaleString()+'</small></div><button class="secondary" data-open="'+esc(x.id)+'">Open</button></div>').join('')||'<div class="muted">No records.</div>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{current=records.find(x=>x.id===b.dataset.open);fillIdentify();renderAll();nav('review')})}
function exportJson(){const blob=new Blob([JSON.stringify(records,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='quality-inspections-backup.json';a.click();URL.revokeObjectURL(a.href)}
init();})();